/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TestRouteImport } from "./routes/test";
import { Route as RouteRouteImport } from "./routes/route";
import { Route as AuthSignupRouteImport } from "./routes/_auth/signup";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as AppHomeRouteImport } from "./routes/_app/home";
import { Route as AppHomeTaskIdRouteImport } from "./routes/_app/home/task/$id";

const TestRoute = TestRouteImport.update({
  id: "/test",
  path: "/test",
  getParentRoute: () => rootRouteImport,
} as any);
const RouteRoute = RouteRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: "/_auth/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/_auth/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AppHomeRoute = AppHomeRouteImport.update({
  id: "/_app/home",
  path: "/home",
  getParentRoute: () => rootRouteImport,
} as any);
const AppHomeTaskIdRoute = AppHomeTaskIdRouteImport.update({
  id: "/task/$id",
  path: "/task/$id",
  getParentRoute: () => AppHomeRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof RouteRoute;
  "/test": typeof TestRoute;
  "/home": typeof AppHomeRouteWithChildren;
  "/login": typeof AuthLoginRoute;
  "/signup": typeof AuthSignupRoute;
  "/home/task/$id": typeof AppHomeTaskIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof RouteRoute;
  "/test": typeof TestRoute;
  "/home": typeof AppHomeRouteWithChildren;
  "/login": typeof AuthLoginRoute;
  "/signup": typeof AuthSignupRoute;
  "/home/task/$id": typeof AppHomeTaskIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof RouteRoute;
  "/test": typeof TestRoute;
  "/_app/home": typeof AppHomeRouteWithChildren;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/signup": typeof AuthSignupRoute;
  "/_app/home/task/$id": typeof AppHomeTaskIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/test" | "/home" | "/login" | "/signup" | "/home/task/$id";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/test" | "/home" | "/login" | "/signup" | "/home/task/$id";
  id:
    | "__root__"
    | "/"
    | "/test"
    | "/_app/home"
    | "/_auth/login"
    | "/_auth/signup"
    | "/_app/home/task/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute;
  TestRoute: typeof TestRoute;
  AppHomeRoute: typeof AppHomeRouteWithChildren;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/test": {
      id: "/test";
      path: "/test";
      fullPath: "/test";
      preLoaderRoute: typeof TestRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof RouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/signup": {
      id: "/_auth/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof AuthSignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/home": {
      id: "/_app/home";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof AppHomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/home/task/$id": {
      id: "/_app/home/task/$id";
      path: "/task/$id";
      fullPath: "/home/task/$id";
      preLoaderRoute: typeof AppHomeTaskIdRouteImport;
      parentRoute: typeof AppHomeRoute;
    };
  }
}

interface AppHomeRouteChildren {
  AppHomeTaskIdRoute: typeof AppHomeTaskIdRoute;
}

const AppHomeRouteChildren: AppHomeRouteChildren = {
  AppHomeTaskIdRoute: AppHomeTaskIdRoute,
};

const AppHomeRouteWithChildren =
  AppHomeRoute._addFileChildren(AppHomeRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  TestRoute: TestRoute,
  AppHomeRoute: AppHomeRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
